version: '3'

services:
  mongo:
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
        - ./data:/data
    networks:
      - mongo-compose-network


networks:
  mongo-compose-network:
    driver: bridge